/* 
 * File:   copleycommandinterface.h
 * Author: Raad Sys
 *
 * Created on 31 August, 2015, 8:13 AM
 */

#ifndef COPLEYCOMMANDINTERFACE_H
#define	COPLEYCOMMANDINTERFACE_H

#ifdef	__cplusplus
extern "C" {
#endif

#include "events.h"
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>

#define MAX_COPLEY_COMAMND_LEN 40
#define MAX_COPLEY_MESG_SIZE 30U



typedef enum
{
    COPLEY_SET_ACCEL_TIME,
    COPLEY_SET_DECEL_TIME,
    COPLEY_SET_VELOCITY,
    COPLEY_SET_TARGET,
    COPLEY_SET_ABORT_DECEL_TIME,
    COPLEY_SET_JERK_RATE,
    COPLEY_SET_DESIRED_STATE,
    COPLEY_SET_PROFILE_TYPE,
    COPLEY_GET_ACTUAL_POSITION,
    COPLEY_SET_CURRENT_POSITION_ZERO,        
    COPLEY_GET_STATUS,
    COPLEY_START_MOVE,
    COPLEY_STOP_MOVE,
    COPLEY_SET_DISABLE_DRIVER,
    COPLEY_GET_TRAJECTORY_STATUS,
    /////////////////////////////////////        
        COPLEY_SET_EN_AMP_PGM_POSITION,
        COPLEY_SET_DISABLE_AMP,
        COPLEY_SET_RESET_AMP,   
        COPLEY_GET_EPORT_CURRENT_MOTOR_POSITION,
        COPLEY_SET_OUT0_TRACK_BIT_EVENT_STATUS,
        COPLEY_SET_OUT0_TRACK_BIT_LATCHED_EVENT_STATUS,
        COPLEY_SET_OUT0_TRACK_BIT_MANUAL_OUTPUT_CON_REG,
        COPLEY_SET_OUT0_TRACK_BIT_TRAJECTORY_STATUS_REG,
        COPLAY_SET_OUT0_GO_ACTIVE_POSITION_BETWEEN_WORD_23_45_IF_BET12_SET_COMMANDED_POSITION,
        COPLEY_SET_OUT0_GO_ACTIVE_POSITION_BETWEEN_WORD_23_45_IF_BET12_CLEAR_ACTUAL_POSITION,
        COPLEY_SET_OUT0_GO_LOWTOHIGH_CROSS_WORD_23_45_IF_BET12_SET_COMMAND_POSITION,
        COPLEY_SET_OUT0_GO_LOWTOHIGH_CROSS_WORD_23_45_IF_BET12_CLEAR_ACTUAL_POSITION,
        COPLEY_SET_OUT0_GO_HIGHTOLOW_CROSS_WORD_23_45_IF_BET12_SET_COMMAND_POSITION,
        COPLEY_SET_OUT0_GO_HIGHTOLOW_CROSS_WORD_23_45_IF_BET12_CLEAR_ACTUAL_POSITION,
        COPLEY_SET_OUT0_GO_ANY_CROSS_WORD_23_45_IF_BET12_SET_COMMAND_POSITION,
        COPLEY_SET_OUT0_GO_ANY_CROSS_WORD_23_45_IF_BET12_CLEAR_ACTUAL_POSITION,
        COPLEY_SET_OUT0_GO_ACTIVE_MOTOR_PHASE_0TO180,
        COPLEY_SET_OUT0_PULSE_POSITION_CROSS_ARRAY_POSITION_STORED_TRACE_MEMORY,
        COPLEY_SET_OUT0_OUTPUT_TRIGGER_EXTERNAL_REGEN_RESISTER,
        COPLEY_SET_OUT0_ETHERCAT_DRIVES_PULSE_SYNC0_SIGNAL,
        COPLEY_SET_OUT0_TRACK_HARDWARE_POSITION,
        COPLEY_SET_INT0_NO_FUNCTION,
        COPLEY_SET_INT0_RESERVED_FOR_FUTURE_USE,
        COPLEY_SET_INT0_RESET_DRIVE_RISING_EDGE_INPUT,
        COPLEY_SET_INT0_RESET_DRIVE_FALLING_EDGE_INPUT,
        COPLEY_SET_INT0_POSITIVE_LIMIT_SWITCH_ACTIVE_HIGH,
        COPLEY_SET_INT0_POSITIVE_LIMIT_SWITCH_ACTIVE_LOW,
        COPLEY_SET_INT0_NEGATIVE_LIMIT_SWITCH_ACTIVE_HIGH,
        COPLEY_SET_INT0_NEGATIVE_LIMIT_SWITCH_ACTIVE_LOW,
        COPLEY_SET_INT0_MOTOR_TEMP_SWITCH_ACTIVE_HIGH,
        COPLEY_SET_INT0_MOTOR_TEMP_SWITCH_ACTIVE_LOW,
        COPLEY_SET_INT0_CLEAR_FAULT_RISING_EDGE_DISABLE_WHILE_HIGH,
        COPLEY_SET_INT0_CLEAR_FAULT_RISING_EDGE_DISABLE_WHILE_LOW,
        COPLEY_SET_INT0_RESET_RISING_EDGE_DISABLE_DRIVE_WHILE_HIGH,
        COPLEY_SET_INT0_RESET_FALLING_EDGE_DISABLE_DRIVE_WHILE_LOW,
        COPLEY_SET_INT0_HOME_SWITCH_ACTIVE_HIGH,
        COPLEY_SET_INT0_HOME_SWITCH_ACTIVE_LOW,
        COPLEY_SET_INT0_DRIVE_DISABLE_ACTIVE_HIGH,
        COPLEY_SET_INT0_DRIVE_DISABLE_ACTIVE_LOW,
        COPLEY_SET_INT0_SYNC_INPUT_FALLING_EDGE,
        COPLEY_SET_INT0_HALT_MOTOR_ACTIVE_HIGH,
        COPLEY_SET_INT0_HALT_MOTOR_ASTIVE_LOW,
        COPLEY_SET_INT0_SCALE_ANALOG_INPUT_WHEN_HIGH,
        COPLEY_SET_INT0_SCALE_ANALOG_INPUT_WHEN_LOW,
        COPLEY_SET_INT0_HIGH_SPEED_POSITION_CAPTURE_RISING_EDGE,
        COPLEY_SET_INT0_HIGH_SPEED_POSITION_CAPTURE_FALLING_EDGE,
        COPLEY_SET_INT0_COUNT_RISING_EDGE_INPUT_INDEXER_REG,
        COPLEY_SET_INT0_COUNT_FALLING_EDGE_INPUT_INDEXER_REGISTER,
        COPLEY_SET_INT0_ENCODER_FAULT_INPUT_ACTIVE_HIGH,
        COPLEY_SET_INT0_ENCODER_FAULT_INPUT_ACTIVE_LOW,
        COPLEY_SET_INT0_ABORT_MOVE_RISING_EDGE_IF_GREATER_NCOUNTS_FROM_DESTINATION_POSITION,
        COPLEY_SET_INT0_ABORT_MOVE_FALLING_EDGE_IF_GREATER_NCOUNTS_FROM_DESTINATION_POSITION,
        COPLEY_SET_INT0_MARK_HV_LOSS_RISING_EDGE_DISABLE_WHILE_HIGH,
        COPLEY_SET_INT0_MARK_HV_LOSS_RISING_EDGE_DISABLE_WHILE_LOW,
        COPLEY_SET_INT0_UPDATE_TRAJECTORY_RISING_EDGE,
        COPLEY_SET_INT0_UPDATE_TRAJECTORY_FALLING_EDGE,
        COPLEY_SET_INT0_CLEAR_FAULT_AND_EVENT_LATCH_RISING_EDGE,
        COPLEY_SET_INT0_CLEAR_FAULT_AND_EVENT_LATCH_FALLING_EDGE,
        COPLEY_SET_INT0_DISABLE_ENCODER_OUTPUT_WHEN_LOW_BURST_CURRENT_POSITION_ENCODER_OUTPUT_FALLING_EDGE,
        COPLEY_SET_INT0_DISABLE_ENCODER_OUTPUT_WHEN_HIGH_BURST_CURRENT_POSITION_ENCODER_OUTPUT_FALLING_EDGE,
        COPLEY_GET_LATCHED_EVENT_STATUS_REG,
        COPLEY_GET_DRIVE_EVENT_STATUS_REG,
        COPLEY_GET_COMMANDED_POSITION,
        COPLEY_GET_FOLLOWING_ERROR,
        COPLEY_GET_MOTOR_CURRENT,
        /*GAINS*/  
        /*Current Loop*/
        COPLEY_SET_PEAK_CURRENT_LIMIT,
        COPLEY_SET_I2T_TIME_LIMIT,
        COPLEY_SET_CONTINUOUS_CURRENT_LIMIT,
        COPLEY_SET_CURRENT_LOOP_OFFSET,
        COPLEY_CURRENT_LOOP_PROPORTIONAL_GAIN,
        COPLEY_CURRENT_LOOP_INTEGRAL_GAIN,
        /*Velocity Loop*/
        COPLEY_SET_VELOCITY_LOOP_VELOCITY_LIMIT,
        COPLEY_SET_VELOCITY_LOOP_ACCELERATION_LIMIT,
        COPLEY_SET_VELOCITY_LOOP_DECELERATION_LIMIT,
        COPLEY_FAST_STOP_RAMP,
        COPLEY_VELOCITY_LOOP_PROPORTIONAL_GAIN,
        COPLEY_VELOCITY_LOOP_INTEGRAL_GAIN,
        /*Position Loop*/
        COPLEY_POSITION_LOOP_PROPORTIONAL_GAIN,
        COPLEY_VELOCITY_FEED_FORWARD,
        COPLEY_ACCELERATION_FEED_FORWARD,
        COPLEY_POSITION_LOOP_GAIN_MULTIPLIER,
        
        COPLEY_GET_ACCEL_TIME,
        COPLEY_GET_DECEL_TIME,
        COPLEY_GET_VELOCITY,
        COPLEY_GET_TARGET,
        COPLEY_GET_ABORT_DECEL_TIME,
        COPLEY_GET_JERK_RATE,
            
         /*Current Loop*/
        COPLEY_GET_PEAK_CURRENT_LIMIT,
        COPLEY_GET_I2T_TIME_LIMIT,
        COPLEY_GET_CONTINUOUS_CURRENT_LIMIT,
        COPLEY_GET_CURRENT_LOOP_OFFSET,
        COPLEY_GET_CURRENT_LOOP_PROPORTIONAL_GAIN,
        COPLEY_GET_CURRENT_LOOP_INTEGRAL_GAIN,
        /*Velocity Loop*/
        COPLEY_GET_VELOCITY_LOOP_VELOCITY_LIMIT,
        COPLEY_GET_VELOCITY_LOOP_ACCELERATION_LIMIT,
        COPLEY_GET_VELOCITY_LOOP_DECELERATION_LIMIT,
        COPLEY_GET_FAST_STOP_RAMP,
        COPLEY_GET_VELOCITY_LOOP_PROPORTIONAL_GAIN,
        COPLEY_GET_VELOCITY_LOOP_INTEGRAL_GAIN,
        /*Position Loop*/
        COPLEY_GET_POSITION_LOOP_PROPORTIONAL_GAIN,
        COPLEY_GET_VELOCITY_FEED_FORWARD,
        COPLEY_GET_ACCELERATION_FEED_FORWARD,
        COPLEY_GET_POSITION_LOOP_GAIN_MULTIPLIER,    
            
        COPLEY_SET_CURRENT_POS_AS_HOME,
        COPLEY_SET_SLOW_HOME_VELOCITY,
        COPLEY_SET_HOME_ACCELARATION,
        COPLEY_SET_IN2_HOME_ACTIVE_LOW,
        COPLEY_SET_IN2_HOME_ACTIVE_HIGH,
        COPLEY_SET_HOME_DIRECTION_MOVE_POSITIVE,
        COPLEY_SET_HOME_DIRECTION_MOVE_NEGATIVE,
        COPLEY_SET_POSITIVE_HARDSTOP_HOME,
        COPLEY_SET_NEGATIVE_HARDSTOP_HOME,
        COPLEY_START_HOME,    
        COPLEY_SET_IN2_ACTIVE_HIGH,
        COPLEY_SET_IN2_ACTIVE_LOW,    
        COPLEY_SET_HOME_OFFSET, 
        COPLEY_SET_IN2_POSITIVE_LIM_SW_ACTIVE_HIGH,
        COPLEY_SET_IN2_POSITIVE_LIM_SW_ACTIVE_LOW,
        COPLEY_SET_IN2_NEGATIVE_LIM_SW_ACTIVE_HIGH,
        COPLEY_SET_IN2_NEGATIVE_LIM_SW_ACTIVE_LOW,
        COPLEY_SET_CLEAR_FAULTS,
        COPLEY_SET_FAST_HOME_VELOCITY,
        COPLEY_SET_HOME_TYPE,
        COPLEY_SET_HOME_CURRENTLIMIT,
        COPLEY_SET_HOME_CURRENTLIMITDELAY,
        COPLEY_GET_MOTOR_TORQUE,    
    COPLEY_MAX_COMMAND
}eCommandToCopley;


  typedef struct
  {
    uint8_t ucCommandWord[MAX_COPLEY_COMAMND_LEN];
    eCommandToCopley eCommandID;
    uint16_t uiCommandLength;
  }copleyCommandTable;
    


static const copleyCommandTable sCopleyCommandTable [COPLEY_MAX_COMMAND] =
{
    {"s r0xcc ", COPLEY_SET_ACCEL_TIME,8U},
    {"s r0xcd ", COPLEY_SET_DECEL_TIME,8U},
    {"s r0xcb ", COPLEY_SET_VELOCITY,8U},
    {"s r0xca ", COPLEY_SET_TARGET,8U},
    {"s r0xcf ", COPLEY_SET_ABORT_DECEL_TIME,8U},
    {"s r0xce ", COPLEY_SET_JERK_RATE,8U},
    {"s r0x24 ", COPLEY_SET_DESIRED_STATE,8U},
    {"s r0xc8 ", COPLEY_SET_PROFILE_TYPE,8U},
    {"g r0x32" , COPLEY_GET_ACTUAL_POSITION,7U},
    {"s r0x32 0", COPLEY_SET_CURRENT_POSITION_ZERO,9U},
    {"g r0xa0", COPLEY_GET_STATUS,7U},
    {"t 1",      COPLEY_START_MOVE,3U},
    {"t 0",      COPLEY_STOP_MOVE,3U},
    {"s r0x24 ", COPLEY_SET_DISABLE_DRIVER,8U},
    {"g r0xc9", COPLEY_GET_TRAJECTORY_STATUS,7U},
    ////////////////////////////////////////////////
    {"s r0x24 21", COPLEY_SET_EN_AMP_PGM_POSITION, 10U},
    {"s r0x24 0", COPLEY_SET_DISABLE_AMP, 9U},
    {"r", COPLEY_SET_RESET_AMP, 1U},
    //{" ", COPLEY_SET_CURRENT_POSITION_ZERO, 1U},
    {"g r0x32", COPLEY_GET_EPORT_CURRENT_MOTOR_POSITION, 7U},
    {"s r0x70 0", COPLEY_SET_OUT0_TRACK_BIT_EVENT_STATUS, 9U},
    {"s r0x70 1", COPLEY_SET_OUT0_TRACK_BIT_LATCHED_EVENT_STATUS, 9U},
    {"s r0x70 2", COPLEY_SET_OUT0_TRACK_BIT_MANUAL_OUTPUT_CON_REG, 9U},
    {"s r0x70 3", COPLEY_SET_OUT0_TRACK_BIT_TRAJECTORY_STATUS_REG, 9U},
    {"s r0x70 516", COPLAY_SET_OUT0_GO_ACTIVE_POSITION_BETWEEN_WORD_23_45_IF_BET12_SET_COMMANDED_POSITION, 11U},
    {"s r0x70 4", COPLEY_SET_OUT0_GO_ACTIVE_POSITION_BETWEEN_WORD_23_45_IF_BET12_CLEAR_ACTUAL_POSITION, 9U},
    {"s r0x70 517", COPLEY_SET_OUT0_GO_LOWTOHIGH_CROSS_WORD_23_45_IF_BET12_SET_COMMAND_POSITION, 11U},
    {"s r0x70 5", COPLEY_SET_OUT0_GO_LOWTOHIGH_CROSS_WORD_23_45_IF_BET12_CLEAR_ACTUAL_POSITION, 9U},
    {"s r0x70 518", COPLEY_SET_OUT0_GO_HIGHTOLOW_CROSS_WORD_23_45_IF_BET12_SET_COMMAND_POSITION, 11U},
    {"s r0x70 6", COPLEY_SET_OUT0_GO_HIGHTOLOW_CROSS_WORD_23_45_IF_BET12_CLEAR_ACTUAL_POSITION, 9U},
    {"s r0x70 519",  COPLEY_SET_OUT0_GO_ANY_CROSS_WORD_23_45_IF_BET12_SET_COMMAND_POSITION, 11U},
    {"s r0x70 7", COPLEY_SET_OUT0_GO_ANY_CROSS_WORD_23_45_IF_BET12_CLEAR_ACTUAL_POSITION, 9U},
    {"s r0x70 8", COPLEY_SET_OUT0_GO_ACTIVE_MOTOR_PHASE_0TO180, 9U},
    {"s r0x70 9", COPLEY_SET_OUT0_PULSE_POSITION_CROSS_ARRAY_POSITION_STORED_TRACE_MEMORY, 9U},
    {"s r0x70 10", COPLEY_SET_OUT0_OUTPUT_TRIGGER_EXTERNAL_REGEN_RESISTER, 10U},
    {"s r0x70 11", COPLEY_SET_OUT0_ETHERCAT_DRIVES_PULSE_SYNC0_SIGNAL,10U},
    {"s r0x70 16", COPLEY_SET_OUT0_TRACK_HARDWARE_POSITION, 11U},
    {"s r0x78 0", COPLEY_SET_INT0_NO_FUNCTION, 9U},
    {"s r0x78 1", COPLEY_SET_INT0_RESERVED_FOR_FUTURE_USE, 9U},
    {"s r0x78 2", COPLEY_SET_INT0_RESET_DRIVE_RISING_EDGE_INPUT, 9U},
    {"s r0x78 3", COPLEY_SET_INT0_RESET_DRIVE_FALLING_EDGE_INPUT, 9U},
    {"s r0x78 4", COPLEY_SET_INT0_POSITIVE_LIMIT_SWITCH_ACTIVE_HIGH, 9U},
    {"s r0x78 5", COPLEY_SET_INT0_POSITIVE_LIMIT_SWITCH_ACTIVE_LOW, 9U},
    {"s r0x78 6", COPLEY_SET_INT0_NEGATIVE_LIMIT_SWITCH_ACTIVE_HIGH, 9U},
    {"s r0x78 7", COPLEY_SET_INT0_NEGATIVE_LIMIT_SWITCH_ACTIVE_LOW, 9U},
    {"s r0x78 8", COPLEY_SET_INT0_MOTOR_TEMP_SWITCH_ACTIVE_HIGH, 9U},
    {"s r0x78 9", COPLEY_SET_INT0_MOTOR_TEMP_SWITCH_ACTIVE_LOW, 9U},
    {"s r0x78 10", COPLEY_SET_INT0_CLEAR_FAULT_RISING_EDGE_DISABLE_WHILE_HIGH, 10U},
    {"s r0x78 11", COPLEY_SET_INT0_CLEAR_FAULT_RISING_EDGE_DISABLE_WHILE_LOW, 10U},
    {"s r0x78 12", COPLEY_SET_INT0_RESET_RISING_EDGE_DISABLE_DRIVE_WHILE_HIGH, 10U},
    {"s r0x78 13", COPLEY_SET_INT0_RESET_FALLING_EDGE_DISABLE_DRIVE_WHILE_LOW, 10U},
    {"s r0x78 14", COPLEY_SET_INT0_HOME_SWITCH_ACTIVE_HIGH, 10U},
    {"s r0x78 15", COPLEY_SET_INT0_HOME_SWITCH_ACTIVE_LOW, 10U},
    {"s r0x78 16", COPLEY_SET_INT0_DRIVE_DISABLE_ACTIVE_HIGH, 10U},
    {"s r0x78 17", COPLEY_SET_INT0_DRIVE_DISABLE_ACTIVE_LOW, 10U},
    {"s r0x78 19", COPLEY_SET_INT0_SYNC_INPUT_FALLING_EDGE, 10U},
    {"s r0x78 20", COPLEY_SET_INT0_HALT_MOTOR_ACTIVE_HIGH, 10U},
    {"s r0x78 21", COPLEY_SET_INT0_HALT_MOTOR_ASTIVE_LOW, 10U},
    {"s r0x78 22", COPLEY_SET_INT0_SCALE_ANALOG_INPUT_WHEN_HIGH, 10U},
    {"s r0x78 23", COPLEY_SET_INT0_SCALE_ANALOG_INPUT_WHEN_LOW, 10U},
    {"s r0x78 24", COPLEY_SET_INT0_HIGH_SPEED_POSITION_CAPTURE_RISING_EDGE, 10U},
    {"s r0x78 25", COPLEY_SET_INT0_HIGH_SPEED_POSITION_CAPTURE_FALLING_EDGE, 10U},
    {"s r0x78 26", COPLEY_SET_INT0_COUNT_RISING_EDGE_INPUT_INDEXER_REG, 10U},
    {"s r0x78 27", COPLEY_SET_INT0_COUNT_FALLING_EDGE_INPUT_INDEXER_REGISTER, 10U},
    {"s r0x78 28", COPLEY_SET_INT0_ENCODER_FAULT_INPUT_ACTIVE_HIGH, 10U},
    {"s r0x78 29", COPLEY_SET_INT0_ENCODER_FAULT_INPUT_ACTIVE_LOW, 10U},
    {"s r0x78 36", COPLEY_SET_INT0_ABORT_MOVE_RISING_EDGE_IF_GREATER_NCOUNTS_FROM_DESTINATION_POSITION, 10U},
    {"s r0x78 37", COPLEY_SET_INT0_ABORT_MOVE_FALLING_EDGE_IF_GREATER_NCOUNTS_FROM_DESTINATION_POSITION, 10U},
    {"s r0x78 38", COPLEY_SET_INT0_MARK_HV_LOSS_RISING_EDGE_DISABLE_WHILE_HIGH, 10U},
    {"s r0x78 39", COPLEY_SET_INT0_MARK_HV_LOSS_RISING_EDGE_DISABLE_WHILE_LOW, 10U},
    {"s r0x78 40", COPLEY_SET_INT0_UPDATE_TRAJECTORY_RISING_EDGE, 10U},
    {"s r0x78 41", COPLEY_SET_INT0_UPDATE_TRAJECTORY_FALLING_EDGE, 10U},
    {"s r0x78 42", COPLEY_SET_INT0_CLEAR_FAULT_AND_EVENT_LATCH_RISING_EDGE, 10U},
    {"s r0x78 43", COPLEY_SET_INT0_CLEAR_FAULT_AND_EVENT_LATCH_FALLING_EDGE, 10U},
    {"s r0x78 44", COPLEY_SET_INT0_DISABLE_ENCODER_OUTPUT_WHEN_LOW_BURST_CURRENT_POSITION_ENCODER_OUTPUT_FALLING_EDGE, 10U},
    {"s r0x78 45", COPLEY_SET_INT0_DISABLE_ENCODER_OUTPUT_WHEN_HIGH_BURST_CURRENT_POSITION_ENCODER_OUTPUT_FALLING_EDGE, 10U},
    {"g r0xa4", COPLEY_GET_LATCHED_EVENT_STATUS_REG, 7U},
    {"g r0xa0", COPLEY_GET_DRIVE_EVENT_STATUS_REG, 7U},
    {"g r0x3d", COPLEY_GET_COMMANDED_POSITION, 7U},
    {"g r0x35", COPLEY_GET_FOLLOWING_ERROR, 7U},
    {"g r0x38", COPLEY_GET_MOTOR_CURRENT, 7U},
    
    {"s f0x21 ", COPLEY_SET_PEAK_CURRENT_LIMIT, 8U},
    {"s f0x23 ", COPLEY_SET_I2T_TIME_LIMIT, 8U},
    {"s f0x22 ", COPLEY_SET_CONTINUOUS_CURRENT_LIMIT, 8U},
    {"s f0xae ", COPLEY_SET_CURRENT_LOOP_OFFSET, 8U},
    
    {"s f0x00 ", COPLEY_CURRENT_LOOP_PROPORTIONAL_GAIN, 8U},
    {"s f0x01 ", COPLEY_CURRENT_LOOP_INTEGRAL_GAIN, 8U},
    {"s f0x3a ", COPLEY_SET_VELOCITY_LOOP_VELOCITY_LIMIT, 8U},
    {"s f0x36 ", COPLEY_SET_VELOCITY_LOOP_ACCELERATION_LIMIT, 8U},
    {"s f0x37 ", COPLEY_SET_VELOCITY_LOOP_DECELERATION_LIMIT, 8U},
    {"s f0xcf ", COPLEY_FAST_STOP_RAMP, 8U},
    {"s f0x27 ", COPLEY_VELOCITY_LOOP_PROPORTIONAL_GAIN, 8U},
    {"s f0x28 ", COPLEY_VELOCITY_LOOP_INTEGRAL_GAIN, 8U},
    {"s f0x30 ", COPLEY_POSITION_LOOP_PROPORTIONAL_GAIN, 8U},
    {"s f0x33 ", COPLEY_VELOCITY_FEED_FORWARD, 8U},
    {"s f0x34 ", COPLEY_ACCELERATION_FEED_FORWARD, 8U},
    {"s f0xe3 ", COPLEY_POSITION_LOOP_GAIN_MULTIPLIER, 8U},
    
    
    
    {"g r0xcc", COPLEY_GET_ACCEL_TIME,7U},
    {"g r0xcd", COPLEY_GET_DECEL_TIME,7U},
    {"g r0xcb", COPLEY_GET_VELOCITY,7U},
    {"g r0xca", COPLEY_GET_TARGET,7U},
    {"g r0xcf", COPLEY_GET_ABORT_DECEL_TIME,7U},
    {"g r0xce", COPLEY_GET_JERK_RATE,7U},
    
    
    {"g f0x21", COPLEY_GET_PEAK_CURRENT_LIMIT, 7U},
    {"g f0x23", COPLEY_GET_I2T_TIME_LIMIT, 7U},
    {"g f0x22", COPLEY_GET_CONTINUOUS_CURRENT_LIMIT, 7U},
    {"g f0xae", COPLEY_GET_CURRENT_LOOP_OFFSET, 7U},
    
    {"g f0x00", COPLEY_GET_CURRENT_LOOP_PROPORTIONAL_GAIN, 7U},
    {"g f0x01", COPLEY_GET_CURRENT_LOOP_INTEGRAL_GAIN, 7U},
    {"g f0x3a", COPLEY_GET_VELOCITY_LOOP_VELOCITY_LIMIT, 7U},
    {"g f0x36", COPLEY_GET_VELOCITY_LOOP_ACCELERATION_LIMIT, 7U},
    {"g f0x37", COPLEY_GET_VELOCITY_LOOP_DECELERATION_LIMIT, 7U},
    {"g f0xcf", COPLEY_GET_FAST_STOP_RAMP, 7U},
    {"g f0x27", COPLEY_GET_VELOCITY_LOOP_PROPORTIONAL_GAIN, 7U},
    {"g f0x28", COPLEY_GET_VELOCITY_LOOP_INTEGRAL_GAIN, 7U},
    {"g f0x30", COPLEY_GET_POSITION_LOOP_PROPORTIONAL_GAIN, 7U},
    {"g f0x33", COPLEY_GET_VELOCITY_FEED_FORWARD, 7U},
    {"g f0x34", COPLEY_GET_ACCELERATION_FEED_FORWARD, 7U},
    {"g f0xe3", COPLEY_GET_POSITION_LOOP_GAIN_MULTIPLIER, 7U},

    {"s r0xc2 512", COPLEY_SET_CURRENT_POS_AS_HOME,11U},
    {"s r0xc4 ", COPLEY_SET_SLOW_HOME_VELOCITY,8U},
    {"s r0xc5 ", COPLEY_SET_HOME_ACCELARATION,8U},
    {"s r0x79 15", COPLEY_SET_IN2_HOME_ACTIVE_LOW,10U},
    {"s r0x79 14", COPLEY_SET_IN2_HOME_ACTIVE_HIGH,10U},
    {"s r0xc2 546", COPLEY_SET_HOME_DIRECTION_MOVE_POSITIVE,11U},
    {"s r0xc2 562", COPLEY_SET_HOME_DIRECTION_MOVE_NEGATIVE,11U},
    {"s r0xc2 516", COPLEY_SET_POSITIVE_HARDSTOP_HOME,11U},
    {"s r0xc2 532", COPLEY_SET_NEGATIVE_HARDSTOP_HOME,11U},
    {"t 2",      COPLEY_START_HOME,3U},
    
    
    {"s r0xa5 2", COPLEY_SET_IN2_ACTIVE_HIGH,9U},
    {"s r0xa5 0", COPLEY_SET_IN2_ACTIVE_LOW,9U},
    {"s r0xc6 ", COPLEY_SET_HOME_OFFSET,8U},
    {"s r0x79 4", COPLEY_SET_IN2_POSITIVE_LIM_SW_ACTIVE_HIGH,9U},
    {"s r0x79 5", COPLEY_SET_IN2_POSITIVE_LIM_SW_ACTIVE_LOW,9U},
    {"s r0x79 6", COPLEY_SET_IN2_NEGATIVE_LIM_SW_ACTIVE_HIGH,9U},
    {"s r0x79 7", COPLEY_SET_IN2_NEGATIVE_LIM_SW_ACTIVE_LOW,9U},
    {"s r0xa4 0xffffffff",COPLEY_SET_CLEAR_FAULTS, 18U},
    {"s r0xc3 ",COPLEY_SET_FAST_HOME_VELOCITY, 8U},
    {"s r0xc2 ",COPLEY_SET_HOME_TYPE, 8U},
    {"s r0xc7 ",COPLEY_SET_HOME_CURRENTLIMIT,8U},
    {"s r0xbf ",COPLEY_SET_HOME_CURRENTLIMITDELAY,8U},
};//COPLEY_GET_DRIVE_EVENT_STATUS_REG: for current move complete 2. COPLEY_GET_EPORT_CURRENT_MOTOR_POSITION : for current position
  
#ifdef	__cplusplus
}
#endif

#endif	/* COPLEYCOMMANDINTERFACE_H */

